"""Add HITL review tables

Revision ID: b83ce7b2044f
Revises: 
Create Date: 2026-01-01 19:03:57.480385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83ce7b2044f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hitl_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('expert_id', sa.String(length=100), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('feedback_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('idx_hitl_feedback_created_at', 'hitl_feedback', ['created_at'], unique=False)
    op.create_index('idx_hitl_feedback_expert', 'hitl_feedback', ['expert_id'], unique=False)
    op.create_index('idx_hitl_feedback_review_id', 'hitl_feedback', ['review_id'], unique=False)
    op.create_table('hitl_reviews',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('review_type', sa.Enum('ANALYSIS_REVIEW', 'QA_REVIEW', name='reviewtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', name='reviewstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='reviewpriority'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('evaluation_data', sa.JSON(), nullable=True),
    sa.Column('assigned_expert_id', sa.String(length=100), nullable=True),
    sa.Column('expert_id', sa.String(length=100), nullable=True),
    sa.Column('expert_notes', sa.Text(), nullable=True),
    sa.Column('validation_result', sa.Enum('APPROVED', 'REJECTED', 'NEEDS_REVISION', name='validationresult'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_hitl_reviews_created_at', 'hitl_reviews', ['created_at'], unique=False)
    op.create_index('idx_hitl_reviews_expert', 'hitl_reviews', ['assigned_expert_id'], unique=False)
    op.create_index('idx_hitl_reviews_priority', 'hitl_reviews', ['priority'], unique=False)
    op.create_index('idx_hitl_reviews_status', 'hitl_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hitl_reviews_status', table_name='hitl_reviews')
    op.drop_index('idx_hitl_reviews_priority', table_name='hitl_reviews')
    op.drop_index('idx_hitl_reviews_expert', table_name='hitl_reviews')
    op.drop_index('idx_hitl_reviews_created_at', table_name='hitl_reviews')
    op.drop_table('hitl_reviews')
    op.drop_index('idx_hitl_feedback_review_id', table_name='hitl_feedback')
    op.drop_index('idx_hitl_feedback_expert', table_name='hitl_feedback')
    op.drop_index('idx_hitl_feedback_created_at', table_name='hitl_feedback')
    op.drop_table('hitl_feedback')
    # ### end Alembic commands ###

